package lockfile

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/undont/supplyscan/internal/types"
)

func TestDetectAndParse_Poetry(t *testing.T) {
	content := `# This file is automatically @generated by Poetry.
[[package]]
name = "flask"
version = "2.0.1"
description = "A simple framework"
category = "main"
optional = false

[[package]]
name = "PyTorch-Lightning"
version = "1.9.0"
description = "deep learning framework"

[[package]]
name = "pytest"
version = "7.4.0"
category = "dev"
optional = false

[metadata]
lock-version = "1.1"

[metadata.files]
flask = []
`
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "poetry.lock")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	lf, err := DetectAndParse(path)
	if err != nil {
		t.Fatalf("DetectAndParse() error = %v", err)
	}
	if lf.Type() != "poetry" {
		t.Errorf("Type() = %q, want poetry", lf.Type())
	}

	deps := lf.Dependencies()
	byName := make(map[string]types.Dependency)
	for _, dep := range deps {
		if dep.Ecosystem != types.EcosystemPyPI {
			t.Errorf("dep %q ecosystem = %q, want pypi", dep.Name, dep.Ecosystem)
		}
		byName[dep.Name] = dep
	}

	if byName["flask"].Version != "2.0.1" {
		t.Errorf("flask version = %q, want 2.0.1", byName["flask"].Version)
	}
	// the [metadata.files] table must not bleed a bogus flask entry back in
	if len(deps) != 3 {
		t.Errorf("len(deps) = %d, want 3 (%v)", len(deps), byName)
	}
	if _, ok := byName["pytorch-lightning"]; !ok {
		t.Errorf("missing PEP 503 normalised 'pytorch-lightning', got %v", byName)
	}
	if !byName["pytest"].Dev {
		t.Error("pytest should be flagged Dev (category = dev)")
	}
	if byName["flask"].Dev {
		t.Error("flask should not be flagged Dev (category = main)")
	}
}
